---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-creds
  namespace: argocd-image-updater
spec:
  encryptedData:
    github.password: AgA4NjqkVUBol8fnlGTt4aQiOYz9/OLxteHI/F3JGeWXnUqFsT+u+2GYSp1PsB/OoZDZ55NmD3IxUglD8vWEZGEmfN/i+mb2XazmFrhXIHEW/E6a7WpevQBbeOOA+oAC9Fjc+hNcpWykIHWR7OY8L9/BOqlRQm9mOT4v3ZkxmztAp7eQKt5/SjKD/IfYorTqFgulR2zhduQqyfv1BWo7vckqH0LnagOOOUI2sjl6OYGDA3k26phAxkrB1l3kwNofWSxwZhplpZF2u5iT7OzstY6MN9fsbWMqgNJLTaaU/VZJL+JA3MFFQmnyaRVu4kM0y7KX1MnV+20a5NrlXdWjnG/U7Vqi8pe8hwup9svxpMjhVCd/vMKoKSxV1eg8WrWtXt7o9g/t8/Uch8npxWIp3JNJyFfv/Ve6Jky4WlkLmbUoIUVBGX5JqRssn6a6XoMDyl+AnGkLYpIVy0qi9xcf5euqmJUfogUzkR/xHjlrHfcJu3z1PZRtVVM1H2EH+ff8nX3jii0sABQh5RWJoHTr1YdvNM55j7FZ705avr8stwIFR6n3rHbdGU2BNCLSpZfQkmuV2N02JyiQkUIW9mYg7Z9aOg4mKAXh3mInCBCEbFZha0XPVdfJZU+UJXi7IHkSRGdjm1+bek4nNQXzJNcGzYQ27KZWa2sMWX6adTxE6TI8ufLQzh8s7TAUUp+sf7nRjqJiFm0KB42f7Q7LTILaFKwlKOOUw+/GXScX2UcaRG7V2HiOCNXDqK9b
    github.username: AgCpaEy2mPuwwo2jkhq/z2MlHnK3QVurpcUGhCJdkhkLXPQ37jdZgP8STtmjDDP0OpcOsrukebNAPeFGkRteRVPvPuviesTVTC9KYVUF3XCbb+Uo+arXCvx5NmwVlt2wssJtwzCkrj1uJZE1N8OqBcZWn8dc5WMt/8aMgVyF30owD1b9hQeXbXrPDF0scfpfOMJF4yOpvfvbw96JBcTonGeNM5l9Mlmzul18bFHiRDLWOcNE9u/QJDjUzoX5ZEJonXq7h4rD8umwnDU9/fk7iovn+ER0yTD7cWnHQ/wS3cpikcSsw6J/xUKuGvs3HkTsH9WRWdh402h1i/C0/O0s6ydX6wp4KVBLOe0UoBFDhuVDSvt2142j+mO9cHbYUA2aP5D4qgVQC2KT/qhnqz+/KiYiTs+h/WMjfTFrP382+NH86gJiBoMJy4Eu/LnTn6CkRfY96typSLMo+v5l4Cybf6CRl/QsQkbER0Hw3hpKnsGwSwaaszJy4W1pDXIaQa8e0LUt1KEmB+uL4b87+X2XOlShCwc6ZC7q8EUm9xwlIkr2r7q+w+YZgSC+c5C7JGUd9AYplhU6kYG2Cx2R+KKCyIMLqW0urbo4f4yWW7Aa1ZRpxdEGiNnKR2aqJzwBjoKvLWmSOmNmLHHsWwcNyis090wHiEle2uJdh40RqrMTrDXJQMelu8zWS01GbnJP0TGBT+Rh9/qWUYca1A==
  template:
    metadata:
      name: github-creds
      namespace: argocd-image-updater
