apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  project: vps-jmsola-dev-project
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources: 
    - chart: argocd-image-updater
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 0.12.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true