apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: crypto-stop-loss-bot
  namespace: crypto-stop-loss-bot
spec:
  encryptedData:
    bit2me.api.key: 
    bit2me.api.secret: 
    google.oauth.client.id: 
    google.oauth.client.secret:
    telegram.bot.token:
  template:
    metadata:
      name: crypto-stop-loss-bot
