
apiVersion: v1
kind: Service
metadata:
  name: crypto-stop-loss-bot
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: crypto-stop-loss-bot