apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  labels:
    app.kubernetes.io/name: certificates
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    argocd.argoproj.io/sync-options: Prune=true
spec:
  acme:
# Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-dns
# Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: traefik
    